config/routes.rb
Consumercard::Application.routes.draw do

  scope :e, module: "e" do
    devise_for :operadores, controllers: {
      sessions: "e/sessions"
    }
    resources :transacoes, except: [:edit] do
      collection do
        get :find_cliente, as: :find_cliente
      end
      member do
        get :cancelar
      end
    end
    get "/keep_alive", controller: :transacoes, action: :keep_alive, as: :keep_alive
    root :to => redirect("/e/operadores/sign_in"), as: :operador_root
  end

  scope :admin, module: "admin" do
    resources :admin_users
    resources :franquia_users
    resources :estabelecimento_users
    resources :cities
    resources :parametrizacoes, except: [:destroy]
    resources :config_boletos, except: [:destroy] do
      get :test, on: :collection
    end
    resources :config_pagseguros, except: [:destroy]
    resources :pagamentos do
      put :confirmar, on: :member
    end
    resources :cliente_users do
      member do
        get :emitir_cartao
      end
    end
    resources :operadores
    resources :planos_adesao, except: [:new, :create, :destroy]
    resources :movimentos, only: [:index]
    resources :transacoes, only: [:index, :destroy], as: :admin_transacoes do
      member do
        get :cancelar
      end
    end
    resources :boletos, only: [:show] do
      member do
        get :enviar_email
      end
    end

    resources :auditoria, only: :show
    resources :banners
    resources :anuidades, only: [:index, :create]
    resources :indicacoes_admin, only: [:index]
    resources :tipo_usuarios
    resources :premios
    resources :resgates, only: [:index, :edit, :update], as: :resgate_admin

    devise_for :users, controllers: {
      sessions: "admin/sessions",
      passwords: "admin/passwords"
    }

    resources :password, only: [:index, :update]
    resources :fechamento, only: [:create]
    resources :importacoes, only: [:new, :create]

    root :to => 'home#index', as: :user_root
  end

  devise_for :cliente_users, controllers: {
    registrations: "cliente_user_registrations"
  }

  resources :cliente_users, only: :index, as: :painel_cliente


  resources :home, only: [:index, :create] do
   get :carregar_cidades,  on: :collection
   get :delete_cidade_default, on: :collection
  end

  resources :inicio, only: [:index]
  resources :participar, only: [:index]
  resources :conveniadas, only: [:index]
  resources :contato, only: [:index, :create]
  resources :sobre, only: [:index, :create]
  resources :premiacoes, only: [:index, :show]
  resources :privacidade, only: [:index]
  resources :resgates, only: [:index, :create] do
    get :new, on: :member, as: :new
  end
  resources :sobre, only: [:index]
  resources :estimativa_ganhos, only: [:index]
  resources :anuidades, only: [:index, :create, :new, :show], as: :public_anuidade
  resources :transacoes, only: [:index], as: :public_transacoes
  resources :conta_corrente, only: [:index]
  resources :indicacoes, only: [:new, :create]
  resources :termo_cadastro, only: [:new, :create, :destroy]
  resources :cep, only: [:show]
  resources :cartoes, only: [:index, :create]

  if Rails.env.production?
    get "/404", :to => "errors#not_found"
    get "/422", :to => "errors#unacceptable"
    get "/500", :to => "errors#internal_error"
  end

  root :to => 'home#index'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CookieHelper

  layout "inicial"
  
  skip_before_filter :verifica_cidade_ativa

	def index
    if cookies[:cidade_default]
      redirect_to inicio_index_url
    end
		@ufs = {"" => "Selecione um Estado"}.merge UF.somente_com_cidade
	end

  def carregar_cidades
    @cidades = City.somente_cidades_com_franquia.where(uf: params[:uf]).order(:description).to_a unless params[:uf].blank?
  end
  
  def create
    if params[:cidade].blank?
      redirect_to home_index_url
    else 
      gravar_cidade_default params[:cidade]
      cookie_indicante = indicante
      if cookie_indicante
        cliente_user = ClienteUser.find(indicante[:id].to_i)
        deletar_indicante if cliente_user && cliente_user.cities[0].id != params[:cidade].to_i
      end

      redirect_to inicio_index_url
    end
  end
  
  def delete_cidade_default
    cookies.delete :cidade_default
    redirect_to home_index_url
  end
	
end

app/helpers/e/home_helper.rb
module E::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def message_config_boleto
    if [FranquiaUser,AdminUser].include? current_user.class
      "Verifique as configurações para emissão de boleto" if !current_user_unico_admin.config_boleto
    end
  end

  def message_config_pagseguro
    "Verifique as configurações do PagSeguro" if current_user_unico_admin.is_a?(FranquiaUser) && !current_user_unico_admin.config_pagseguro
  end
end

app/views/home/carregar_cidades.js.erb
var options = [];
options.push($("<option>").attr("value", "0").text("Selecione uma Cidade"));
<% @cidades.to_a.each do |cidade| %>
  options.push($("<option>").attr("value", "<%= cidade.id %>").text("<%= cidade.description %>"));
<% end %>
$("#cidade").html(options).css("visibility", "visible").focus();

app/views/home/index.html.erb
<table style="width: 100%; height: 100%">
  <tr valign="middle">
    <td align="center">
      <div class="container form-inicio" style="width: 350px !important">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <%= image_tag "frontend/logoBranco.png", title: "ConsumerCard", alt: "ConsumerCard", style: "width: 90%" %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-sm-offset-2 col-md-offset-2 col-lg-offset-2 text-center">
            <br /><br />
            <%= form_tag carregar_cidades_home_index_path, method: "get", remote: true, id: "form_inicial" do  %>
              <%= select_tag :uf, options_for_select(@ufs.collect{|k,v|[v,k]}), class:"form-control input-sm", autofocus: true, style: "height: 27px" %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-sm-offset-2 col-md-offset-2 col-lg-offset-2 text-center">
              <br />
              <%= form_tag  home_index_path do  %>
                <select id="cidade" name="cidade" class="form-control input-sm" style="visibility: hidden; height: 27px"></select>
              <% end %>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>

<%= messages %>