config/routes.rb
Consumercard::Application.routes.draw do

  scope :e, module: "e" do
    devise_for :operadores, controllers: {
      sessions: "e/sessions"
    }
    resources :transacoes, except: [:edit] do
      collection do
        get :find_cliente, as: :find_cliente
      end
      member do
        get :cancelar
      end
    end
    get "/keep_alive", controller: :transacoes, action: :keep_alive, as: :keep_alive
    root :to => redirect("/e/operadores/sign_in"), as: :operador_root
  end

  scope :admin, module: "admin" do
    resources :admin_users
    resources :franquia_users
    resources :estabelecimento_users
    resources :cities
    resources :parametrizacoes, except: [:destroy]
    resources :config_boletos, except: [:destroy] do
      get :test, on: :collection
    end
    resources :config_pagseguros, except: [:destroy]
    resources :pagamentos do
      put :confirmar, on: :member
    end
    resources :cliente_users do
      member do
        get :emitir_cartao
      end
    end
    resources :operadores
    resources :planos_adesao, except: [:new, :create, :destroy]
    resources :movimentos, only: [:index]
    resources :transacoes, only: [:index, :destroy], as: :admin_transacoes do
      member do
        get :cancelar
      end
    end
    resources :boletos, only: [:show] do
      member do
        get :enviar_email
      end
    end

    resources :auditoria, only: :show
    resources :banners
    resources :anuidades, only: [:index, :create]
    resources :indicacoes_admin, only: [:index]
    resources :tipo_usuarios
    resources :premios
    resources :resgates, only: [:index, :edit, :update], as: :resgate_admin

    devise_for :users, controllers: {
      sessions: "admin/sessions",
      passwords: "admin/passwords"
    }

    resources :password, only: [:index, :update]
    resources :fechamento, only: [:create]
    resources :importacoes, only: [:new, :create]

    root :to => 'home#index', as: :user_root
  end

  devise_for :cliente_users, controllers: {
    registrations: "cliente_user_registrations"
  }

  resources :cliente_users, only: :index, as: :painel_cliente


  resources :home, only: [:index, :create] do
   get :carregar_cidades,  on: :collection
   get :delete_cidade_default, on: :collection
  end

  resources :inicio, only: [:index]
  resources :participar, only: [:index]
  resources :conveniadas, only: [:index]
  resources :contato, only: [:index, :create]
  resources :sobre, only: [:index, :create]
  resources :premiacoes, only: [:index, :show]
  resources :privacidade, only: [:index]
  resources :resgates, only: [:index, :create] do
    get :new, on: :member, as: :new
  end
  resources :sobre, only: [:index]
  resources :estimativa_ganhos, only: [:index]
  resources :anuidades, only: [:index, :create, :new, :show], as: :public_anuidade
  resources :transacoes, only: [:index], as: :public_transacoes
  resources :conta_corrente, only: [:index]
  resources :indicacoes, only: [:new, :create]
  resources :termo_cadastro, only: [:new, :create, :destroy]
  resources :cep, only: [:show]
  resources :cartoes, only: [:index, :create]

  if Rails.env.production?
    get "/404", :to => "errors#not_found"
    get "/422", :to => "errors#unacceptable"
    get "/500", :to => "errors#internal_error"
  end

  root :to => 'home#index'
end

app/models/resgate.rb
class Resgate < ActiveRecord::Base
  belongs_to :cliente_user
  belongs_to :premio
  after_commit :enviar_email_confirmacao


  def enviar_email_confirmacao
    if self.enviado
      ResgateMailer.notificar_envio(self).deliver
      sms = "[ConsumerCard] Seu prêmio #{self.premio.descricao} acaba de ser enviado para voce. Ele chegara no seu endereço em até #{Parametrizacao.first.prazo_entrega_premio} dias."
      SmsSender.new(self.cliente_user.celular, sms).send
    end
  end
end

app/controllers/admin/resgates_controller.rb
class Admin::ResgatesController < Admin::AdminController
  before_action :set_resgate, only: [:edit, :update]

  def index
    @filter = params[:q]
    @enviado = params[:enviado] || "nao"

    @resgates = Resgate
      .where("users.nome like :filter Or premios.descricao Like :filter", {filter: "%#{@filter}%"})
      .where(":enviado = '' Or (:enviado = 'sim' And enviado) Or (:enviado = 'nao' And Not enviado)", {enviado: @enviado.to_s})
      .joins(:premio, :cliente_user)
      .includes(:premio, :cliente_user)
      .includes({premio: :tipo_usuario})
      .order(:id)
      .page(params[:page])
  end

  def update
    @resgate.update enviado: true
    redirect_to resgate_admin_index_url, notice: "Prêmio enviado"
  end

  private

  def set_resgate
    @resgate = Resgate.find(params[:id])
  end
end

app/controllers/resgates_controller.rb
class ResgatesController < ApplicationController
  before_filter :authenticate_cliente_user!
  layout "painel"

  def index
    @premios = premios_disponiveis.to_a
    @consumo_medio_mensal = current_cliente_user.consumo_medio_mensal(6).to_f
    @limite = @consumo_medio_mensal >= Parametrizacao.first.vlr_consumo_medio_para_resgate_premios.to_f
    maximo_ja_resgatado = Resgate.where(cliente_user: current_cliente_user).joins({premio: :tipo_usuario}).maximum("tipo_usuarios.quantidade_indicacoes").to_i
    @proximo = TipoUsuario.where("quantidade_indicacoes > ?", current_cliente_user.quantidade_indicacoes).first
  end

  def new
    valido = premios_disponiveis.where("premios.id = ?", params[:id].to_i).exists?
    if valido
      @premio = Premio.find(params[:id])
    else
      redirect_to resgates_url, alert: "Prêmio não disponível para você."
    end
  end

  def create
    valido = premios_disponiveis.where("premios.id = ?", params[:premio_id].to_i).exists?
    limite = current_cliente_user.consumo_medio_mensal(6).to_f >= Parametrizacao.first.vlr_consumo_medio_para_resgate_premios.to_f

    raise "Prêmio inválido" unless valido
    raise "Não atingiu limite" unless limite

    ActiveRecord::Base.transaction do
      current_cliente_user.update! cliente_user_params
      Resgate.create! cliente_user: current_cliente_user, premio_id: params[:premio_id].to_i, enviado: false
    end
    redirect_to painel_cliente_index_url, notice: "Quando o prêmio for enviado para o seu endereço, você receberá um e-mail com a confirmação"
  end

  private

  def premios_disponiveis
    Premio.premios_disponiveis_usuario(current_cliente_user)
      .includes(:tipo_usuario)
      .order(:tipo_usuario_id)
  end

  def cliente_user_params
    params.require(:cliente_user).permit(:cep, :cidade, :logradouro, :numero, :bairro, :complemento)
  end
end

app/helpers/admin/resgates_helper.rb
module Admin::ResgatesHelper
  def tr_class_resgate(resgate)
    resgate.enviado ? "success" : "warning"
  end
end

app/views/resgates/_header_privado.html.erb
<% @controle = @controle.to_i + 1 %>

<% if i == 0 || @premios[i].tipo_usuario_id != @premios[i-1].tipo_usuario_id || @controle % 3 == 0 %>

  <% if i != 0 %>
    </div>
  <% end %>

  <% if i == 0 || @premios[i].tipo_usuario_id != @premios[i-1].tipo_usuario_id %>
    <% @controle = 0 %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h3><%= premio.tipo_usuario.descricao %></h3>
      </div>
    </div>
  <% end %>

  <div class="row">
<% end %>

app/views/resgates/_produto_privado.html.erb
<div class="col-xs-6 col-md-3">
  <div class="thumbnail">
    <%= image_tag premio.imagem.url, alt: premio.descricao, title: premio.descricao %>
    <div class="caption">
      <h5 class="text-center"><%= premio.descricao %></h5>
      <%= link_to "Ver mais informações", new_resgate_path(premio.id), class: "btn btn-primary col-md-12" %>
    </div>
  </div>
</div>

app/views/resgates/index.html.erb
<% if @premios.empty? %>
  <%= content_tag :h5, "Você deve ter #{@proximo.quantidade_indicacoes} Pontos de Indicação acumulados para avançar de categoria e solicitar seu prêmio." if @proximo %>
  <%= content_tag :h5, "Nenhum prêmio disponível para resgate" unless @proximo %>
  <h5>Dúvidas? <%= link_to "Consulte a Tabela de Prêmios", premiacoes_path %></h5>
<% elsif @limite %>
  <div class="container">
    <% @premios.each_with_index do |premio, i| %>
      <%= render partial: "header_privado", locals: {premio: premio, i: i} %>
      <%= render partial: "produto_privado", locals: {premio: premio} %>
    <% end %>
    </div> <!-- Fecha Ultima Row -->
  </div>
<% else %>
  <h5>Você não atingiu o Consumo Médio Mensal de <%= Dinheiro.new(Parametrizacao.first.vlr_consumo_medio_para_resgate_premios).real_formatado %> nos últimos 180 dias.<br></h5>
  <h5>Dúvidas? <%= link_to "Consulte o item 7.4 do Regulamento", new_termo_cadastro_path(painel: true) %></h5>
<% end %>

app/views/resgates/new.html.erb
<h2 class="text-center"><%= @premio.descricao %></h2>

<div class="col-md-12">
  <div class="thumbnail" style="border: none; padding: 0; margin: 0">
    <%= image_tag @premio.imagem.url, alt: @premio.descricao, title: @premio.descricao %>
    <div class="caption">
      <p><%= raw @premio.descricao_completa.nl2br %></p>
    </div>
  </div>

  <%= form_for(current_cliente_user, url: resgates_path, method: :post) do |f| %>
    <legend>Confira o endereço para entrega antes de solicitar o prêmio</legend>
    <%= hidden_field_tag :premio_id, @premio.id %>
    <div class="row">
      <div class="<%= get_class_control_form(current_cliente_user, 'cep') %> col-md-3">
        <%= f.label :cep, 'CEP', class: 'control-label' %>
        <%= f.text_field :cep, class: 'form-control', data: {mask: "cep"} %>
        <span class="help-block">
          <a href="http://www.buscacep.correios.com.br/" target="_blank" tabindex="-1">Não sabe o seu cep?</a>
          <%= current_cliente_user.errors.messages[:cep].join %>
        </span>
      </div>

      <div class="<%= get_class_control_form(current_cliente_user, 'cidade') %> col-md-9">
        <%= f.label :cidade, 'Cidade', class: 'control-label' %>
        <%= f.text_field :cidade, class: 'form-control', required: true , readonly: true, tabindex: -1 %>
        <span class="help-block"><%= current_cliente_user.errors.messages[:cidade].join %></span>
      </div>
    </div>

    <div class="row">
      <div class="<%= get_class_control_form(current_cliente_user, 'logradouro') %> col-sm-9">
        <%= f.label :logradouro, 'Logradouro', class: 'control-label' %>
        <%= f.text_field :logradouro, class: 'form-control', required: true %>
        <span class="help-block"><%= current_cliente_user.errors.messages[:logradouro].join %></span>
      </div>

      <div class="<%= get_class_control_form(current_cliente_user, 'numero') %> col-sm-3">
        <%= f.label :numero, 'Número', class: 'control-label' %>
        <%= f.text_field :numero, class: 'form-control', required: true %>
        <span class="help-block"><%= current_cliente_user.errors.messages[:numero].join %></span>
      </div>
    </div>

    <div class="row">
      <div class="<%= get_class_control_form(current_cliente_user, 'bairro') %> col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= f.label :bairro, 'Bairro', class: 'control-label' %>
        <%= f.text_field :bairro, class: 'form-control', required: true %>
        <span class="help-block"><%= current_cliente_user.errors.messages[:bairro].join %></span>
      </div>

      <div class="<%= get_class_control_form(current_cliente_user, 'complemento') %> col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= f.label :complemento, 'Complemento', class: 'control-label' %>
        <%= f.text_field :complemento, class: 'form-control' %>
        <span class="help-block"><%= current_cliente_user.errors.messages[:complemento].join %></span>
      </div>
    </div>

    <%= f.submit 'Solicitar Prêmio', class: 'btn btn-primary', data: {confirm: "Deseja realmente solicitar esse prêmio?"} %>
  <% end %>
</div>